"""dono_id em eventos

Revision ID: 427255bcd800
Revises: 691b7d8b788c
Create Date: 2026-09-17 19:39:40.014464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427255bcd800'
down_revision: Union[str, Sequence[str], None] = '691b7d8b788c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dono_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_eventos_dono', 'usuarios', ['dono_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_constraint('fk_eventos_dono', type_='foreignkey')
        batch_op.drop_column('dono_id')

    # ### end Alembic commands ###
